/* Kaduosi shared i18n — EN default, supports zh/de/es. Include on every page. */
(function(){
  var DICT = {
    en: {
      "meta.title":"Kaduosi | B2B Automotive Interior Systems",
      "meta.description":"Kaduosi supplies global B2B buyers with automotive interior systems: seat covers, exterior accessories, car care, in-car electronics, performance upgrades and specialty vehicle goods.",
      "topbar.group":"▦ Group Websites","topbar.support":"Support","topbar.region":"◎ Select Region / Language",
      "nav.products":"Products","nav.solutions":"Solutions","nav.oem":"OEM Program","nav.resources":"Resources","nav.about":"About Kaduosi","nav.search":"Search","nav.langlabel":"Global - English","nav.contact":"Contact",
      "cat.interior":"Interior Accessories","cat.exterior":"Exterior Accessories","cat.care":"Car Care","cat.electronics":"In-Car Electronics","cat.performance":"Performance Parts","cat.suvrv":"Pickup / SUV / RV","cat.moto":"Motorcycle Parts","cat.safety":"Safety & Emergency","cat.tools":"Repair Tools","cat.gifts":"Travel Gifts",
      "hero.title":"Automotive interior systems for global B2B channels","hero.desc":"Kaduosi organizes automotive seat covers and interior accessories into product systems for distributors, modification studios and private-label buyers.","hero.cta1":"View product systems","hero.cta2":"View channel solutions",
      "rec.title":"Recommended",
      "rec.tag.system":"Product System","rec.tag.exterior":"Exterior System","rec.tag.care":"Car Care","rec.tag.digital":"Digital","rec.tag.upgrade":"Upgrade","rec.tag.specialty":"Specialty","rec.tag.gift":"Gift",
      "rec.desc.interior":"Seat covers, steering wheel covers, lumbar supports, floor mats, storage and comfort add-ons.","rec.desc.exterior":"Exterior styling, trim parts and body protection.","rec.desc.care":"Cleaning, detailing, maintenance and daily-care small parts.","rec.desc.electronics":"In-car electrical parts, electronic devices and smart accessories.","rec.desc.performance":"Performance and structural upgrade parts.","rec.desc.suvrv":"Outdoor and large-vehicle use cases.","rec.desc.gifts":"Channel bundle add-on small parts.",
      "sol.title":"Solutions","sol.contact":"Contact us","sol.pl.title":"For private-label buyers","sol.pl.desc":"Build a sellable interior product line around vehicle lists, material direction, packaging and a sample-to-bulk path.","sol.dist.title":"For distributors","sol.dist.desc":"Product systems built for sell-through and repeat orders.","sol.mod.title":"For modification studios","sol.mod.desc":"Focus on fitment, visual finish and cabin upgrade experience.","sol.ec.title":"For online sellers","sol.ec.desc":"Extend from hero SKUs into bundle sets and add-on items.",
      "stat.cat":"Interior categories","stat.custom":"Custom trial-order path","stat.bulk":"Bulk quantity path","stat.pages":"Catalog pages ready",
      "res.title":"Resources","res.lang":"Choose language","res.a.tag":"Buyer Guide","res.a.title":"How to prepare a custom seat-cover RFQ","res.a.desc":"Vehicle list, market, quantity, material direction and packaging expectations — a stronger starting point.","res.b.tag":"Product System","res.b.title":"Vehicle-fit and universal product programs","res.b.desc":"Vehicle-fit suits high finish quality; universal systems suit channel volume.","res.c.tag":"Private Label","res.c.title":"What assets you need before launch","res.c.desc":"Installation shots, material close-ups, packaging photos and trust proofs.",
      "cta.title":"Start with a serious product direction","cta.desc":"When direction matches, start with vehicle list, market, quantity and sample expectations.","cta.btn":"Contact Kaduosi",
      "foot.company":"Taizhou Kaduosi Import And Export Co., Ltd.<br>Zhejiang, China","foot.products":"Products","foot.solutions":"Solutions","foot.distributors":"Distributors","foot.mod":"Modification Studios","foot.pl":"Private Label","foot.resources":"Resources","foot.buyerguide":"Buyer Guide","foot.oem":"OEM Method","foot.faq":"FAQ","foot.support":"Support","foot.regionlang":"Region / Language","foot.contact":"Contact","foot.about":"About","foot.companylink":"Company","foot.capa":"Capabilities",
      "contact.eyebrow":"Structured RFQ","contact.h1":"Send a clear RFQ, get a sharper quotation.","contact.lead":"The clearer your vehicle list, market, quantity and packaging expectations, the sharper the quotation, sample plan and OEM packaging suggestion you receive.","contact.req.title":"Required information","contact.req.label":"To quote precisely we need:","contact.req.body":"buyer role, vehicle models, target market, first quantity, product route, material and packaging preference.",
      "contact.list.a":"Vehicle models and year range for fitment","contact.list.b":"Target market and channel (distribution / studio / private label / e-commerce)","contact.list.c":"First-order quantity and future volume plan","contact.list.d":"Product route (custom-fit / universal / add-on / sample kit)","contact.list.e":"Material direction and packaging preference",
      "contact.form.title":"Start RFQ","contact.form.role":"Buyer role","contact.form.role.a":"Auto Parts Distributor","contact.form.role.b":"Car Modification Studio","contact.form.role.c":"Private Label Buyer","contact.form.role.d":"E-commerce Seller","contact.form.route":"Program / product route","contact.form.route.a":"Custom Fit Series","contact.form.route.b":"Universal Dealer Series","contact.form.route.c":"Interior Protection Add-ons","contact.form.route.d":"Sample kit first","contact.form.email":"Your email","contact.form.notes":"Vehicle models and market","contact.form.notes.ph":"Vehicle models, country, quantity, material, packaging, deadline...","contact.form.btn":"Open RFQ email draft","contact.form.hint":"Your default email client will open with the message pre-filled.",
      "contact.entity.eyebrow":"Entity information","contact.entity.title":"Company profile for buyer verification","contact.entity.company":"Company","contact.entity.companyVal":"Taizhou Kaduosi Import And Export Co., Ltd.","contact.entity.location":"Location","contact.entity.locationVal":"Zhejiang, China","contact.entity.contact":"Contact","contact.entity.contactVal":"Listed contact: Mr. Wei Tang",
      "contact.cta.title":"Not ready for RFQ yet?","contact.cta.desc":"Browse the product systems first and come back with a specific direction.","contact.cta.btn":"Back to homepage",
      "contact.email.subject":"RFQ from Kaduosi website","contact.email.body":"Buyer role: {role}\nProduct route: {route}\nEmail: {email}\nVehicle models and market:\n{notes}"
    },
    zh: {
      "meta.title":"Kaduosi | 汽车内饰产品系统","meta.description":"Kaduosi 为全球 B2B 买家提供汽车内饰产品系统，包括车内内饰配件、车身外观外饰件、清洁养护、车载电子数码、性能改装与专用场景用品。",
      "topbar.group":"▦ 集团网站","topbar.support":"支持","topbar.region":"◎ 选择区域 / 语言",
      "nav.products":"产品","nav.solutions":"解决方案","nav.oem":"OEM 项目","nav.resources":"资源","nav.about":"关于 Kaduosi","nav.search":"搜索","nav.langlabel":"中国 - 简体中文","nav.contact":"联系我们",
      "cat.interior":"车内内饰配件","cat.exterior":"车身外观外饰件","cat.care":"汽车清洁养护","cat.electronics":"车载电子数码","cat.performance":"性能改装件","cat.suvrv":"皮卡 / SUV / 房车专用","cat.moto":"摩托车配件","cat.safety":"安全应急用品","cat.tools":"维修工具耗材","cat.gifts":"车载出行礼品小件",
      "hero.title":"面向全球 B2B 渠道的汽车内饰系统","hero.desc":"Kaduosi 将汽车座套与汽车内饰配件组织成产品系统，服务分销商、改装店和私标买家。","hero.cta1":"查看产品系统","hero.cta2":"查看渠道解决方案",
      "rec.title":"推荐信息",
      "rec.tag.system":"产品系统","rec.tag.exterior":"外观系统","rec.tag.care":"养护","rec.tag.digital":"数码","rec.tag.upgrade":"改装","rec.tag.specialty":"专用","rec.tag.gift":"礼品",
      "rec.desc.interior":"汽车座套、方向盘套、腰靠、脚垫、储物与舒适加购。","rec.desc.exterior":"外观改装、装饰件与车身防护。","rec.desc.care":"清洁、护理、保养与日常养护小件。","rec.desc.electronics":"车载电器、电子设备与智能配件。","rec.desc.performance":"性能与结构升级配件。","rec.desc.suvrv":"户外与大车型场景。","rec.desc.gifts":"渠道组合销售小件。",
      "sol.title":"解决方案","sol.contact":"联系我们","sol.pl.title":"面向私标买家","sol.pl.desc":"围绕车型清单、材料方向、包装和样品到批量路径，建立可销售的汽车内饰产品线。","sol.dist.title":"面向分销商","sol.dist.desc":"建立更易销售和复购的产品系统。","sol.mod.title":"面向改装店","sol.mod.desc":"聚焦版型、视觉完成度和座舱升级体验。","sol.ec.title":"面向电商卖家","sol.ec.desc":"从核心 SKU 扩展到组合套装和加购品。",
      "stat.cat":"内饰类目","stat.custom":"定制试单路径","stat.bulk":"批发起量路径","stat.pages":"已整理目录页",
      "res.title":"资源","res.lang":"选择语言","res.a.tag":"买家指南","res.a.title":"如何准备定制座套 RFQ","res.a.desc":"车型清单、市场、数量、材料方向和包装预期，是更好的起点。","res.b.tag":"产品体系","res.b.title":"车型定制与通用产品项目","res.b.desc":"车型定制适合高端完成度，通用系统适合渠道放量。","res.c.tag":"私标合作","res.c.title":"投放前需要哪些素材","res.c.desc":"安装图、材料细节、包装图片和信任背书。",
      "cta.title":"从严肃的产品方向开始","cta.desc":"当方向匹配时，从车型清单、市场、数量和样品预期开始沟通。","cta.btn":"联系 Kaduosi",
      "foot.company":"台州卡铎斯进出口有限公司<br>中国 · 浙江","foot.products":"产品","foot.solutions":"解决方案","foot.distributors":"分销商","foot.mod":"改装店","foot.pl":"私标买家","foot.resources":"资源","foot.buyerguide":"买家指南","foot.oem":"OEM 项目方法","foot.faq":"常见问题","foot.support":"支持","foot.regionlang":"区域 / 语言","foot.contact":"联系我们","foot.about":"关于","foot.companylink":"公司介绍","foot.capa":"能力矩阵",
      "contact.eyebrow":"结构化询盘","contact.h1":"发一份清楚的 RFQ，换来更准的报价","contact.lead":"车型清单、市场、数量和包装预期越清楚，我们给出的报价、样品方案和 OEM 包装建议就越精准。","contact.req.title":"需要提供的信息","contact.req.label":"精确报价所需信息：","contact.req.body":"买家角色、车型清单、目标市场、首单数量、产品路线、材料方向与包装偏好。",
      "contact.list.a":"车型清单及年款范围（用于匹配版型）","contact.list.b":"目标市场与渠道（分销 / 改装店 / 私标 / 电商）","contact.list.c":"首单数量与后续放量计划","contact.list.d":"产品路线（车型定制 / 通用 / 加购件 / 样品包）","contact.list.e":"材料方向与包装偏好",
      "contact.form.title":"开始 RFQ","contact.form.role":"买家角色","contact.form.role.a":"汽配分销商","contact.form.role.b":"汽车改装店","contact.form.role.c":"私标买家","contact.form.role.d":"电商卖家","contact.form.route":"项目 / 产品路线","contact.form.route.a":"车型定制系列","contact.form.route.b":"通用经销系列","contact.form.route.c":"内饰保护加购件","contact.form.route.d":"先做样品包","contact.form.email":"您的邮箱","contact.form.notes":"车型清单与目标市场","contact.form.notes.ph":"车型、国家、数量、材料、包装、交期……","contact.form.btn":"生成 RFQ 邮件草稿","contact.form.hint":"系统会调起您的默认邮件客户端，正文已预填好。",
      "contact.entity.eyebrow":"主体信息","contact.entity.title":"用于买家核验的公司资料","contact.entity.company":"公司","contact.entity.companyVal":"台州卡铎斯进出口有限公司","contact.entity.location":"地址","contact.entity.locationVal":"中国 · 浙江","contact.entity.contact":"联系人","contact.entity.contactVal":"对接联系人：Mr. Wei Tang",
      "contact.cta.title":"还没准备好发 RFQ？","contact.cta.desc":"先看一下产品系统，带着更具体的方向再回来沟通。","contact.cta.btn":"返回首页",
      "contact.email.subject":"来自 Kaduosi 官网的 RFQ 询盘","contact.email.body":"买家角色：{role}\n产品路线：{route}\n邮箱：{email}\n车型与市场：\n{notes}"
    },
    de: {
      "meta.title":"Kaduosi | B2B Auto-Innenraumsysteme","meta.description":"Kaduosi liefert weltweiten B2B-Käufern Auto-Innenraumsysteme: Sitzbezüge, Exterieur-Zubehör, Fahrzeugpflege, In-Car Elektronik, Performance-Upgrades und Spezialfahrzeug-Zubehör.",
      "topbar.group":"▦ Gruppenwebsites","topbar.support":"Support","topbar.region":"◎ Region / Sprache wählen",
      "nav.products":"Produkte","nav.solutions":"Lösungen","nav.oem":"OEM-Programm","nav.resources":"Ressourcen","nav.about":"Über Kaduosi","nav.search":"Suche","nav.langlabel":"Deutschland - Deutsch","nav.contact":"Kontakt",
      "cat.interior":"Innenraum-Zubehör","cat.exterior":"Exterieur-Zubehör","cat.care":"Fahrzeugpflege","cat.electronics":"In-Car Elektronik","cat.performance":"Performance-Teile","cat.suvrv":"Pickup / SUV / Wohnmobil","cat.moto":"Motorrad-Teile","cat.safety":"Sicherheit & Notfall","cat.tools":"Reparatur-Werkzeuge","cat.gifts":"Reise-Geschenke",
      "hero.title":"Innenraumsysteme für globale B2B-Kanäle","hero.desc":"Kaduosi organisiert Sitzbezüge und Innenraum-Zubehör zu Produktsystemen für Distributoren, Umbau-Studios und Private-Label-Käufer.","hero.cta1":"Produktsysteme ansehen","hero.cta2":"Kanal-Lösungen ansehen",
      "rec.title":"Empfehlungen",
      "rec.tag.system":"Produktsystem","rec.tag.exterior":"Exterieur-System","rec.tag.care":"Pflege","rec.tag.digital":"Digital","rec.tag.upgrade":"Upgrade","rec.tag.specialty":"Spezial","rec.tag.gift":"Geschenk",
      "rec.desc.interior":"Sitzbezüge, Lenkradbezüge, Lendenstützen, Fußmatten, Aufbewahrung und Komfort-Extras.","rec.desc.exterior":"Exterieur-Styling, Zierteile und Karosserieschutz.","rec.desc.care":"Reinigung, Detailing, Wartung und Pflegezubehör.","rec.desc.electronics":"In-Car-Elektrik, elektronische Geräte und Smart-Zubehör.","rec.desc.performance":"Performance- und Struktur-Upgrade-Teile.","rec.desc.suvrv":"Outdoor- und Großfahrzeug-Szenarien.","rec.desc.gifts":"Kanal-Bundle Kleinteile.",
      "sol.title":"Lösungen","sol.contact":"Kontakt","sol.pl.title":"Für Private-Label-Käufer","sol.pl.desc":"Verkaufsfähige Innenraum-Produktlinien rund um Fahrzeugliste, Materialrichtung, Verpackung und einen Muster-zu-Bulk-Pfad.","sol.dist.title":"Für Distributoren","sol.dist.desc":"Produktsysteme für Abverkauf und Nachbestellung.","sol.mod.title":"Für Umbau-Studios","sol.mod.desc":"Fokus auf Passform, Optik und Innenraum-Upgrade-Erlebnis.","sol.ec.title":"Für Online-Verkäufer","sol.ec.desc":"Von Hero-SKUs zu Bundle-Sets und Add-on-Artikeln erweitern.",
      "stat.cat":"Innenraum-Kategorien","stat.custom":"Kundenspezifischer Musterauftrag","stat.bulk":"Volumen-Bestellpfad","stat.pages":"Katalogseiten fertig",
      "res.title":"Ressourcen","res.lang":"Sprache wählen","res.a.tag":"Käuferleitfaden","res.a.title":"Wie man eine RFQ für maßgeschneiderte Sitzbezüge vorbereitet","res.a.desc":"Fahrzeugliste, Markt, Menge, Materialrichtung und Verpackungserwartungen — ein besserer Startpunkt.","res.b.tag":"Produktsystem","res.b.title":"Fahrzeugspezifische und Universal-Produktprogramme","res.b.desc":"Fahrzeugspezifisch für Premium-Finish; Universal für Kanal-Volumen.","res.c.tag":"Private Label","res.c.title":"Welche Assets Sie vor dem Launch brauchen","res.c.desc":"Installationsaufnahmen, Material-Nahaufnahmen, Verpackungsfotos und Vertrauensnachweise.",
      "cta.title":"Mit einer seriösen Produktrichtung starten","cta.desc":"Wenn die Richtung passt, mit Fahrzeugliste, Markt, Menge und Muster-Erwartungen starten.","cta.btn":"Kaduosi kontaktieren",
      "foot.company":"Taizhou Kaduosi Import And Export Co., Ltd.<br>Zhejiang, China","foot.products":"Produkte","foot.solutions":"Lösungen","foot.distributors":"Distributoren","foot.mod":"Umbau-Studios","foot.pl":"Private Label","foot.resources":"Ressourcen","foot.buyerguide":"Käuferleitfaden","foot.oem":"OEM-Methode","foot.faq":"FAQ","foot.support":"Support","foot.regionlang":"Region / Sprache","foot.contact":"Kontakt","foot.about":"Über","foot.companylink":"Unternehmen","foot.capa":"Fähigkeiten",
      "contact.eyebrow":"Strukturierte RFQ","contact.h1":"Senden Sie eine klare RFQ, erhalten Sie ein präziseres Angebot.","contact.lead":"Je klarer Ihre Fahrzeugliste, Ihr Markt, Ihre Menge und Ihre Verpackungserwartungen sind, desto präziser sind Angebot, Musterplan und OEM-Verpackungsvorschlag.","contact.req.title":"Erforderliche Informationen","contact.req.label":"Für eine präzise Angabe benötigen wir:","contact.req.body":"Käuferrolle, Fahrzeugmodelle, Zielmarkt, Erstmenge, Produktroute, Material und Verpackungspräferenz.",
      "contact.list.a":"Fahrzeugmodelle und Baujahr für die Passform","contact.list.b":"Zielmarkt und Kanal (Distribution / Studio / Private Label / E-Commerce)","contact.list.c":"Erstauftragsmenge und zukünftiger Volumenplan","contact.list.d":"Produktroute (Custom-Fit / Universal / Add-on / Musterkit)","contact.list.e":"Materialrichtung und Verpackungspräferenz",
      "contact.form.title":"RFQ starten","contact.form.role":"Käuferrolle","contact.form.role.a":"Autoteile-Distributor","contact.form.role.b":"Fahrzeug-Umbau-Studio","contact.form.role.c":"Private-Label-Käufer","contact.form.role.d":"E-Commerce-Verkäufer","contact.form.route":"Programm / Produktroute","contact.form.route.a":"Custom-Fit-Serie","contact.form.route.b":"Universal-Händler-Serie","contact.form.route.c":"Innenraum-Schutz Add-ons","contact.form.route.d":"Zuerst Musterkit","contact.form.email":"Ihre E-Mail","contact.form.notes":"Fahrzeugmodelle und Markt","contact.form.notes.ph":"Fahrzeugmodelle, Land, Menge, Material, Verpackung, Frist...","contact.form.btn":"RFQ-E-Mail-Entwurf öffnen","contact.form.hint":"Ihr Standard-E-Mail-Client öffnet sich mit vorausgefülltem Text.",
      "contact.entity.eyebrow":"Firmeninformation","contact.entity.title":"Firmenprofil zur Käuferverifizierung","contact.entity.company":"Firma","contact.entity.companyVal":"Taizhou Kaduosi Import And Export Co., Ltd.","contact.entity.location":"Standort","contact.entity.locationVal":"Zhejiang, China","contact.entity.contact":"Kontakt","contact.entity.contactVal":"Ansprechpartner: Herr Wei Tang",
      "contact.cta.title":"Noch nicht bereit für die RFQ?","contact.cta.desc":"Sehen Sie sich zuerst die Produktsysteme an und kommen Sie mit einer konkreten Richtung zurück.","contact.cta.btn":"Zur Startseite",
      "contact.email.subject":"RFQ von der Kaduosi-Website","contact.email.body":"Käuferrolle: {role}\nProduktroute: {route}\nE-Mail: {email}\nFahrzeugmodelle und Markt:\n{notes}"
    },
    es: {
      "meta.title":"Kaduosi | Sistemas de interior automotriz B2B","meta.description":"Kaduosi suministra a compradores B2B globales sistemas de interior automotriz: fundas de asiento, accesorios exteriores, cuidado del vehículo, electrónica in-car, upgrades de rendimiento y productos para vehículos especiales.",
      "topbar.group":"▦ Sitios del grupo","topbar.support":"Soporte","topbar.region":"◎ Seleccionar región / idioma",
      "nav.products":"Productos","nav.solutions":"Soluciones","nav.oem":"Programa OEM","nav.resources":"Recursos","nav.about":"Acerca de Kaduosi","nav.search":"Buscar","nav.langlabel":"España - Español","nav.contact":"Contacto",
      "cat.interior":"Accesorios interiores","cat.exterior":"Accesorios exteriores","cat.care":"Cuidado del auto","cat.electronics":"Electrónica in-car","cat.performance":"Piezas de rendimiento","cat.suvrv":"Pickup / SUV / RV","cat.moto":"Piezas de moto","cat.safety":"Seguridad y emergencia","cat.tools":"Herramientas de reparación","cat.gifts":"Regalos de viaje",
      "hero.title":"Sistemas de interior automotriz para canales B2B globales","hero.desc":"Kaduosi organiza fundas de asiento y accesorios de interior automotriz en sistemas de producto para distribuidores, talleres de tuning y compradores de marca privada.","hero.cta1":"Ver sistemas de producto","hero.cta2":"Ver soluciones de canal",
      "rec.title":"Recomendados",
      "rec.tag.system":"Sistema de producto","rec.tag.exterior":"Sistema exterior","rec.tag.care":"Cuidado","rec.tag.digital":"Digital","rec.tag.upgrade":"Upgrade","rec.tag.specialty":"Especialidad","rec.tag.gift":"Regalo",
      "rec.desc.interior":"Fundas de asiento, fundas de volante, soportes lumbares, alfombrillas, almacenamiento y confort.","rec.desc.exterior":"Estética exterior, molduras y protección de carrocería.","rec.desc.care":"Limpieza, detailing, mantenimiento y cuidado diario.","rec.desc.electronics":"Electricidad in-car, dispositivos electrónicos y accesorios inteligentes.","rec.desc.performance":"Piezas de mejora de rendimiento y estructura.","rec.desc.suvrv":"Escenarios outdoor y de vehículos grandes.","rec.desc.gifts":"Piezas pequeñas para bundles de canal.",
      "sol.title":"Soluciones","sol.contact":"Contáctenos","sol.pl.title":"Para compradores de marca privada","sol.pl.desc":"Construya una línea de producto vendible en torno a lista de vehículos, dirección de materiales, packaging y ruta de muestra a volumen.","sol.dist.title":"Para distribuidores","sol.dist.desc":"Sistemas de producto pensados para sell-through y recompra.","sol.mod.title":"Para talleres de tuning","sol.mod.desc":"Enfoque en encaje, acabado visual y experiencia de upgrade de cabina.","sol.ec.title":"Para vendedores online","sol.ec.desc":"Extienda de SKUs estrella a bundles y add-ons.",
      "stat.cat":"Categorías de interior","stat.custom":"Ruta de muestra personalizada","stat.bulk":"Ruta de volumen","stat.pages":"Páginas de catálogo listas",
      "res.title":"Recursos","res.lang":"Elegir idioma","res.a.tag":"Guía del comprador","res.a.title":"Cómo preparar un RFQ de fundas de asiento personalizadas","res.a.desc":"Lista de vehículos, mercado, cantidad, dirección de materiales y expectativas de packaging: un mejor punto de partida.","res.b.tag":"Sistema de producto","res.b.title":"Programas de producto específicos y universales","res.b.desc":"Los específicos para acabado premium; los universales para volumen de canal.","res.c.tag":"Marca privada","res.c.title":"Qué activos necesita antes del lanzamiento","res.c.desc":"Fotos de instalación, primeros planos de material, fotos de packaging y pruebas de confianza.",
      "cta.title":"Empiece con una dirección de producto seria","cta.desc":"Cuando la dirección coincide, empiece por lista de vehículos, mercado, cantidad y expectativas de muestra.","cta.btn":"Contactar Kaduosi",
      "foot.company":"Taizhou Kaduosi Import And Export Co., Ltd.<br>Zhejiang, China","foot.products":"Productos","foot.solutions":"Soluciones","foot.distributors":"Distribuidores","foot.mod":"Talleres de tuning","foot.pl":"Marca privada","foot.resources":"Recursos","foot.buyerguide":"Guía del comprador","foot.oem":"Método OEM","foot.faq":"FAQ","foot.support":"Soporte","foot.regionlang":"Región / Idioma","foot.contact":"Contacto","foot.about":"Acerca","foot.companylink":"Empresa","foot.capa":"Capacidades",
      "contact.eyebrow":"RFQ estructurado","contact.h1":"Envíe un RFQ claro y reciba una cotización más precisa.","contact.lead":"Cuanto más clara sea su lista de vehículos, mercado, cantidad y expectativas de packaging, más precisas serán la cotización, el plan de muestras y la propuesta de packaging OEM que reciba.","contact.req.title":"Información requerida","contact.req.label":"Para cotizar con precisión necesitamos:","contact.req.body":"rol del comprador, modelos de vehículos, mercado objetivo, cantidad inicial, ruta de producto, dirección de materiales y preferencia de packaging.",
      "contact.list.a":"Modelos de vehículos y rango de años para el encaje","contact.list.b":"Mercado objetivo y canal (distribución / taller / marca privada / e-commerce)","contact.list.c":"Cantidad de primer pedido y plan de volumen futuro","contact.list.d":"Ruta de producto (custom-fit / universal / add-on / kit de muestra)","contact.list.e":"Dirección de materiales y preferencia de packaging",
      "contact.form.title":"Iniciar RFQ","contact.form.role":"Rol del comprador","contact.form.role.a":"Distribuidor de autopartes","contact.form.role.b":"Taller de tuning","contact.form.role.c":"Comprador de marca privada","contact.form.role.d":"Vendedor de e-commerce","contact.form.route":"Programa / ruta de producto","contact.form.route.a":"Serie Custom-Fit","contact.form.route.b":"Serie Universal para distribuidores","contact.form.route.c":"Add-ons de protección de interior","contact.form.route.d":"Primero kit de muestra","contact.form.email":"Su correo","contact.form.notes":"Modelos de vehículos y mercado","contact.form.notes.ph":"Modelos, país, cantidad, material, packaging, plazo...","contact.form.btn":"Abrir borrador de correo RFQ","contact.form.hint":"Se abrirá su cliente de correo predeterminado con el mensaje pre-completado.",
      "contact.entity.eyebrow":"Información de la entidad","contact.entity.title":"Perfil de empresa para verificación del comprador","contact.entity.company":"Empresa","contact.entity.companyVal":"Taizhou Kaduosi Import And Export Co., Ltd.","contact.entity.location":"Ubicación","contact.entity.locationVal":"Zhejiang, China","contact.entity.contact":"Contacto","contact.entity.contactVal":"Contacto: Sr. Wei Tang",
      "contact.cta.title":"¿Aún no listo para RFQ?","contact.cta.desc":"Explore primero los sistemas de producto y vuelva con una dirección más concreta.","contact.cta.btn":"Volver a inicio",
      "contact.email.subject":"RFQ desde el sitio de Kaduosi","contact.email.body":"Rol del comprador: {role}\nRuta de producto: {route}\nCorreo: {email}\nModelos y mercado:\n{notes}"
    }
  };
  var HTML_LANG = {en:"en", zh:"zh-CN", de:"de", es:"es"};
  function resolveLang(){
    var q = new URLSearchParams(location.search).get("lang");
    if(q && DICT[q]) { try{localStorage.setItem("kd_lang", q);}catch(e){} return q; }
    var s; try{ s = localStorage.getItem("kd_lang"); }catch(e){}
    if(s && DICT[s]) return s;
    var nav = (navigator.language||"en").toLowerCase();
    if(nav.indexOf("zh")===0) return "zh";
    if(nav.indexOf("de")===0) return "de";
    if(nav.indexOf("es")===0) return "es";
    return "en";
  }
  function applyLang(lang){
    var d = DICT[lang] || DICT.en;
    document.documentElement.setAttribute("lang", HTML_LANG[lang] || "en");
    document.querySelectorAll("[data-i18n]").forEach(function(el){
      var k = el.getAttribute("data-i18n");
      var v = d[k];
      if(v === undefined) return;
      var attr = el.getAttribute("data-i18n-attr");
      if(attr){ el.setAttribute(attr, v); }
      else if(el.tagName === "TITLE"){ document.title = v; }
      else{ el.innerHTML = v; }
    });
  }
  window.__kdDict = DICT;
  var lang = resolveLang();
  applyLang(lang);
  window.__kdSetLang = function(l){ if(!DICT[l]) return; try{localStorage.setItem("kd_lang", l);}catch(e){} applyLang(l); };
})();
